name: Test Cask

on:
  pull_request:
    paths:
      - Casks/**
  push:
    branches:
      - main
    paths:
      - Casks/**

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test cask
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git show
          brew tap bryango/ccswitch "$PWD"
          brew style --cask bryango/ccswitch/cc-switch
          brew audit --cask bryango/ccswitch/cc-switch
          brew install --cask bryango/ccswitch/cc-switch
